[INFO     2010-03-10 08:51:01,125 bulkloader.py] Logging to bulkloader-log-20100310.085101
[INFO     2010-03-10 08:51:01,125 bulkloader.py] Throttling transfers:
[INFO     2010-03-10 08:51:01,125 bulkloader.py] Bandwidth: 250000 bytes/second
[INFO     2010-03-10 08:51:01,125 bulkloader.py] HTTP connections: 8/second
[INFO     2010-03-10 08:51:01,125 bulkloader.py] Entities inserted/fetched/modified: 20/second
[INFO     2010-03-10 08:51:01,125 bulkloader.py] Opening database: bulkloader-progress-20100310.085101.sql3
[DEBUG    2010-03-10 08:51:01,467 bulkloader.py] [Thread-1] RestoreThread: started
[DEBUG    2010-03-10 08:51:01,473 bulkloader.py] [Thread-1] RestoreThread: exiting
[DEBUG    2010-03-10 08:51:01,484 bulkloader.py] [Thread-2] RestoreThread: started
[DEBUG    2010-03-10 08:51:01,484 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: started
[DEBUG    2010-03-10 08:51:01,486 adaptive_thread_pool.py] [WorkerThread-1] WorkerThread: started
[DEBUG    2010-03-10 08:51:01,486 adaptive_thread_pool.py] [WorkerThread-2] WorkerThread: started
[DEBUG    2010-03-10 08:51:01,486 adaptive_thread_pool.py] [WorkerThread-3] WorkerThread: started
[DEBUG    2010-03-10 08:51:01,487 adaptive_thread_pool.py] [WorkerThread-4] WorkerThread: started
[DEBUG    2010-03-10 08:51:01,487 adaptive_thread_pool.py] [WorkerThread-5] WorkerThread: started
[DEBUG    2010-03-10 08:51:01,489 adaptive_thread_pool.py] [WorkerThread-6] WorkerThread: started
[DEBUG    2010-03-10 08:51:01,489 adaptive_thread_pool.py] [WorkerThread-7] WorkerThread: started
[DEBUG    2010-03-10 08:51:01,490 adaptive_thread_pool.py] [WorkerThread-8] WorkerThread: started
[DEBUG    2010-03-10 08:51:01,490 adaptive_thread_pool.py] [WorkerThread-9] WorkerThread: started
[DEBUG    2010-03-10 08:51:01,490 bulkloader.py] Configuring remote_api. url_path = /remote_api, servername = khanexercises.appspot.com
[DEBUG    2010-03-10 08:51:01,492 bulkloader.py] Bulkloader using app_id: khanexercises
[DEBUG    2010-03-10 08:51:01,492 bulkloader.py] [Thread-2] RestoreThread: exiting
[INFO     2010-03-10 08:51:01,493 bulkloader.py] Connecting to khanexercises.appspot.com/remote_api
[ERROR    2010-03-10 08:51:10,668 bulkloader.py] Exception during authentication
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\bulkloader.py", line 3158, in Run
    self.request_manager.Authenticate()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\bulkloader.py", line 1169, in Authenticate
    remote_api_stub.MaybeInvokeAuthentication()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", line 539, in MaybeInvokeAuthentication
    datastore_stub._server.Send(datastore_stub._path, payload=None)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py", line 346, in Send
    f = self.opener.open(req)
  File "C:\Python26\lib\urllib2.py", line 395, in open
    response = meth(req, response)
  File "C:\Python26\lib\urllib2.py", line 508, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python26\lib\urllib2.py", line 433, in error
    return self._call_chain(*args)
  File "C:\Python26\lib\urllib2.py", line 367, in _call_chain
    result = func(*args)
  File "C:\Python26\lib\urllib2.py", line 516, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
[INFO     2010-03-10 08:51:10,680 bulkloader.py] Authentication Failed
